FROM node:21-alpine3.19 as deps
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci

FROM node:21-alpine3.19 as builder

ARG ORDERS_DATABASE_URL
ENV DATABASE_URL=$ORDERS_DATABASE_URL

WORKDIR /usr/src/app
COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY . .

RUN npx prisma migrate deploy
RUN npx prisma generate

RUN npm run build
RUN npm ci -f --omit=dev && npm cache clean --force

FROM node:21-alpine3.19 as runner
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=deps /usr/src/app/package*.json ./
COPY --from=builder /usr/src/app/prisma ./prisma

ENV NODE_ENV=production

USER node

EXPOSE 3000
CMD ["node", "dist/main.js"]