version: '3'

services:
  orders-db:
    container_name: orders_database
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ordersdb
    volumes:
      - ./postgres:/var/lib/postgresql/data
